CREATE TABLE IF NOT EXISTS conversations (id TEXT PRIMARY KEY, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, summary TEXT NOT NULL DEFAULT '', turn_count INTEGER NOT NULL DEFAULT 0, consent INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS messages (id INTEGER PRIMARY KEY AUTOINCREMENT, conversation_id TEXT NOT NULL, role TEXT NOT NULL, content TEXT NOT NULL, created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS idx_messages_conversation ON messages(conversation_id,id);
CREATE TABLE IF NOT EXISTS leads (conversation_id TEXT PRIMARY KEY, data TEXT NOT NULL, updated_at INTEGER NOT NULL, status TEXT NOT NULL DEFAULT 'exploring');
CREATE TABLE IF NOT EXISTS meetings (id TEXT PRIMARY KEY, conversation_id TEXT NOT NULL, email TEXT NOT NULL, starts_at TEXT NOT NULL, ends_at TEXT NOT NULL, calendar_event_id TEXT NOT NULL, reminder_day INTEGER NOT NULL DEFAULT 0, reminder_hour INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS rate_limits (key TEXT PRIMARY KEY, count INTEGER NOT NULL, expires_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS events (id INTEGER PRIMARY KEY AUTOINCREMENT, conversation_id TEXT, name TEXT NOT NULL, created_at INTEGER NOT NULL);
